# Generated by Django 4.1.7 on 2023-03-05 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('nations', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='nationitem',
            unique_together={('nation', 'item_type', 'item_id')},
        ),
    ]
