# Generated by Django 4.1.7 on 2023-03-05 17:52

from django.db import migrations, models

import applications.nations.models


class Migration(migrations.Migration):

    dependencies = [
        ('nations', '0003_alter_nationitem_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nation',
            name='flag',
            field=models.ImageField(blank=True, null=True, upload_to=applications.nations.models.flag_upload),
        ),
    ]
