# Generated by Django 4.1.7 on 2023-03-11 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nations', '0005_nationitem_disabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='NationBuilding',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('nations.nationitem',),
        ),
        migrations.CreateModel(
            name='NationResource',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('nations.nationitem',),
        ),
    ]
