# Generated by Django 4.1.7 on 2023-03-31 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import misc.files


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alliances', '0002_alter_alliance_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alliancemember',
            options={'ordering': ['rank', 'joined_at']},
        ),
        migrations.AddField(
            model_name='alliance',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=misc.files.PathAndRename('alliance_banners')),
        ),
        migrations.CreateModel(
            name='AllianceApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alliance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='alliances.alliance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alliance_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
