# Development overrides
services:
  web:
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./webserver:/home/app/webserver  # for live refresh/debug
    environment:
      DJANGO_CONFIGURATION: Development

  queue_worker:
    volumes:
      - ./webserver:/home/app/webserver  # for live refresh/debug
    environment:
        DJANGO_CONFIGURATION: Development

  frontend:  # live refresh works like shit
    command: npm run watch
    volumes:
      - ./frontend:/home/app/web  # for live refresh
      - /home/app/web/node_modules  # to persevere node_modules

  db:
    ports:
      - "5432:5432"
    networks:
      - default
      - internal
