# Development overrides
services:
  web:
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./webserver:/home/app/webserver  # for live refresh/debug
    environment:
      DJANGO_CONFIGURATION: Development

  queue_worker:
    volumes:
      - ./webserver:/home/app/webserver  # for live refresh/debug
    environment:
        DJANGO_CONFIGURATION: Development

  frontend:  # live refresh works like shit
    command: npm run watch
    volumes:
      - ./frontend:/home/app/web  # for live refresh

  db:
    ports:
      - "5432:5432"
    networks:
      - default
      - internal

#  pgadmin:
#    image: dpage/pgadmin4
#    container_name: clop-pgadmin
#    restart: unless-stopped
#    security_opt:
#      - no-new-privileges:true
#    networks:
#      - internal
#    ports:
#      - "5050:80"
#    environment:
#      PGADMIN_DEFAULT_EMAIL: admin@admin.com
#      PGADMIN_DEFAULT_PASSWORD: root
#      PGADMIN_LISTEN_PORT: 80
