# Generated by Django 4.1.7 on 2023-03-25 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('nations', '0006_nationbuilding_nationresource'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.PositiveIntegerField()),
                ('amount', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('order_type', models.PositiveSmallIntegerField(choices=[(1, 'Buy'), (2, 'Sell')])),
                ('item_type', models.ForeignKey(limit_choices_to={'model__in': ('resource',)}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('nation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nations.nation')),
            ],
        ),
    ]
