# Generated by Django 4.1.7 on 2023-03-06 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_bundleitem_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='items/icons'),
        ),
        migrations.AddField(
            model_name='resource',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='items/icons'),
        ),
    ]
