# Generated by Django 4.1.7 on 2023-03-11 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_building_icon_resource_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='NationRecipe',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('items.recipe',),
        ),
    ]
