# Generated by Django 4.1.7 on 2023-03-12 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nationreport',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Recipe'), (2, 'Destroy'), (3, 'Tick')]),
        ),
    ]
