# Generated by Django 4.1.7 on 2023-03-12 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_nationreport_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nationreport',
            old_name='level',
            new_name='report_type',
        ),
    ]
