# Generated by Django 4.1.7 on 2023-04-02 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_nationreport_report_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nationreport',
            options={'ordering': ['-created_on']},
        ),
        migrations.RenameField(
            model_name='nationreport',
            old_name='created_at',
            new_name='created_on',
        ),
    ]
